### ISSUE TITLE
item can select then error genrate is can not find variable :item

### ISSUE THREAD

**Issue by nkbeldar** [vishaldhanotiya/react-native-modal-picker#11]
i can select country in picker  then error generate is "can't find variable :item"
please resolve this error apas

**Comment by vishaldhanotiya** [comment]
Can you please add code here because i have test code in both platform but not finding this issue??

**Comment by nkbeldar** [comment]
import React from 'react';
import { FlatList, ScrollView, Text, View,TouchableOpacity,StyleSheet, TouchableHighlight, Image ,StatusBar,TextInput,Picker} from 'react-native';
import styles from './styles';
import { recipes } from '../../data/dataArrays';
import MenuImage from '../../components/MenuImage/MenuImage';
import DrawerActions from 'react-navigation';
import { getCategoryName } from '../../data/MockDataAPI';
import RNPicker from "rn-modal-picker";
var item = [
  {
    id: 1,
    name: "Afghanistan"
  },
  {
    id: 2,
    name: "Bahrain"
  },
  {
    id: 3,
    name: "Canada"
  },
  {
    id: 4,
    name: "Denmark"
  },
  {
    id: 5,
    name: "Egypt"
  },
  {
    id: 6,
    name: "France"
  },
  {
    id: 7,
    name: "Greece"
  },
  {
    id: 8,
    name: "Hong Kong"
  },
  {
    id: 9,
    name: "India"
  },
  {
    id: 10,
    name: "Japan"
  },
  {
    id: 11,
    name: "Kenya"
  },
  {
    id: 12,
    name: "Liberia"
  }
];

export default class HomeScreen extends React.Component {

  state = {user: '',user2: '',user3: '',
  dataSource: [
    {
      id: 1,
      name: "Afghanistan"
    },
    {
      id: 2,
      name: "Bahrain"
    },
    {
      id: 3,
      name: "Canada"
    },
    {
      id: 4,
      name: "Denmark"
    },
    {
      id: 5,
      name: "Egypt"
    },
    {
      id: 6,
      name: "France"
    },
    {
      id: 7,
      name: "Greece"
    },
    {
      id: 8,
      name: "Hong Kong"
    },
    {
      id: 9,
      name: "India"
    },
    {
      id: 10,
      name: "Japan"
    },
    {
      id: 11,
      name: "Kenya"
    },
    {
      id: 12,
      name: "Liberia"
    }
  ],
  placeHolderText: "Please Select Country",
  selectedText: ""}
  updateuser = (user) => {
     this.setState({ user: user })
  }
  updateUser2 = (user2) => {
    this.setState({ user2: user2 })
 }
 updateUser3 = (user3) => {
  this.setState({ user: user3 })
}
_selectedValue(index, item) {
  this.setState({ selectedText: item.name });
}

  static navigationOptions = ({ navigation }) => ({
    title: 'Paypal Calculator',
    headerStyle: {
      backgroundColor: '#2680EB',
      
    },
    headerTintColor: '#fff',
    headerTitleStyle: {
      fontFamily: "Arvo-Bold"
    },
    headerLeft: (
      <MenuImage
        onPress={() => {
          navigation.openDrawer();
        }}
      />
    )
  });

 
  


  render() {
    return (
      <View>
        <StatusBar
            barStyle="dark-content"
            // dark-content, light-content and default
            hidden={false}
            //To hide statusBar
            backgroundColor="#2680EB"
            //Background color of statusBar
            translucent={false}
            //allowing light, but not detailed shapes
            networkActivityIndicatorVisible={true}
          />
      <View>
      <Text style={{marginLeft:15,paddingTop:20,color:'black', fontFamily:'Arvo-Bold',fontSize:22}}>Payment Ammount</Text>
      <TextInput style={{   margin: 15,
      height: 50,
      borderColor: 'black',
      borderRadius:5,
      borderWidth: 1}}
               underlineColorAndroid = "transparent"
               autoCapitalize = "none"
               onChangeText = {this.Ammount}/>
       <Text style={{marginLeft:15,color:'black', fontFamily:'Arvo-Bold'}}>Currency</Text>
       <View style={{   margin: 15,
      height: 50,
      borderRadius:5,
      borderColor: 'black',
      borderWidth: 1}} >
       <Picker selectedValue = {this.state.user} onValueChange = {this.updateuser}>
              
               <Picker.Item label = "Australian dollar (AUD)" value = "1" />
               <Picker.Item label = "Brazilian real (BRL)" value = "2" />
               <Picker.Item label = "Canadian dollar	(CAD)" value = "3" />
               <Picker.Item label = "Czech koruna	(CZK)" value = "4" />
               <Picker.Item label = "Danish krone	(DKK)" value = "5" />
               <Picker.Item label = "Euro (EUR)" value = "6" />
               <Picker.Item label = "Hong Kong dollar	(HKD)" value = "7" />
               <Picker.Item label = "Indian rupee (INR)" value = "8" />
               <Picker.Item label = "Israeli new shekel (ILS)	" value = "9" />
               <Picker.Item label = "Japanese yen (JPY)" value = "10" />
               <Picker.Item label = "Malaysian ringgit  (MYR)" value = "11" />
               <Picker.Item label = "Mexican peso	(MXN)" value = "12" />
               <Picker.Item label = "New Taiwan dollar (TWD)" value = "13" />
               <Picker.Item label = "New Zealand dollar	(NZD)" value = "14" />
               <Picker.Item label = "Norwegian krone	(NOK)" value = "15" />
               <Picker.Item label = "Philippine peso (PHP)	" value = "16" />
               <Picker.Item label = "Polish złoty	(PLN)" value = "17" />
               <Picker.Item label = "Pound sterling	(GBP)" value = "18" />
               <Picker.Item label = "Russian ruble (RUB)	" value = "19" />
               <Picker.Item label = "Singapore dollar	(SGD)" value = "20" />
               <Picker.Item label = "Swedish krona (SEK)	" value = "21" />
               <Picker.Item label = "Thai baht (THB)	" value = "22" />
               <Picker.Item label = "United States dollar (USD)	" value = "23" />
            </Picker>
       </View>
       <Text style={{marginLeft:15,color:'black',fontFamily:'Arvo-Bold'}}>Receiver's Country</Text>
       <View  >
       <RNPicker
          dataSource={this.state.dataSource}
          dummyDataSource={this.state.dataSource}
          defaultValue={false}
          pickerTitle={"Country Picker"}
          showSearchBar={true}
          disablePicker={false}
          changeAnimation={"none"}
          searchBarPlaceHolder={"Search....."}
          showPickerTitle={true}
          searchBarContainerStyle={this.props.searchBarContainerStyle}
          pickerStyle={Styles.pickerStyle}
          pickerItemTextStyle={Styles.listTextViewStyle}
          selectedLabel={this.state.selectedText}
          placeHolderLabel={this.state.placeHolderText}
          selectLabelTextStyle={Styles.selectLabelTextStyle}
          placeHolderTextStyle={Styles.placeHolderTextStyle}
          dropDownImageStyle={Styles.dropDownImageStyle}
         
          selectedValue={(index, name,) => this._selectedValue(index, item)}
        />
       </View>
       <Text style={{marginLeft:15,color:'black',fontFamily:'Arvo-Bold'}}>Fee Rate</Text>
       <View style={{   margin: 15,
      height: 50,
      borderColor: 'black',
      borderRadius:5,
      borderWidth: 1}} >
       <Picker selectedValue = {this.state.user3} onValueChange = {this.updateUser3}>
               <Picker.Item label = "Steve" value = "steve" />
               <Picker.Item label = "Ellen" value = "ellen" />
               <Picker.Item label = "Maria" value = "maria" />
            </Picker>
       </View>
       <View style={{flexDirection:'row',alignItems:'center',justifyContent:'center'}}>
       <TouchableOpacity style={{marginLeft:15, height: 50,width:150,backgroundColor:'#2680EB',borderRadius:10}}>
        <Text style={{textAlign:'center',color:'white',fontFamily:'Arvo-Bold',padding:13}}>To Send</Text>
      </TouchableOpacity>
      <TouchableOpacity style={{marginLeft:15, height: 50,width:150,backgroundColor:'#2680EB',borderRadius:10}}>
        <Text style={{textAlign:'center',color:'white',fontFamily:'Arvo-Bold',padding:13}}>To Received</Text>
      </TouchableOpacity>
       </View>
     
      </View>
      </View>
    );
  }
}
const Styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center"
  },

  searchBarContainerStyle: {
    marginBottom: 10,
    flexDirection: "row",
    height: 50,
    width:250,
    shadowOpacity: 1.0,
    shadowRadius: 5,
    shadowOffset: {
      width: 1,
      height: 1
    },
    backgroundColor: "rgba(255,255,255,1)",
    shadowColor: "#d3d3d3",
    borderRadius: 10,
    elevation: 3,
    marginLeft: 10,
    marginRight: 10
  },

  selectLabelTextStyle: {
    color: "#000",
    textAlign: "left",
    width: "99%",
    padding: 10,
    flexDirection: "row"
  },
  placeHolderTextStyle: {
    color: "#D3D3D3",
    padding: 10,
    textAlign: "left",
    width: "99%",
    flexDirection: "row"
  },
  dropDownImageStyle: {
    marginLeft: 10,
    width: 10,
    height: 10,
    alignSelf: "center"
  },
  listTextViewStyle: {
    color: "black",
    marginVertical: 10,
    flex: 0.9,
    marginLeft: 20,
    marginHorizontal: 10,
    textAlign: "left"
  },
  pickerStyle: {
    marginLeft: 18,
    elevation:3,
    paddingRight: 25,
    marginRight: 10,
    marginBottom: 2,
    shadowOpacity: 1.0,
    shadowOffset: {
      width: 1,
      height: 1
    },
    borderWidth:1,
    shadowRadius: 10,
    backgroundColor: "rgba(255,255,255,1)",
    shadowColor: "#d3d3d3",
    borderRadius: 5,
    flexDirection: "row"
  }
});

**Comment by vishaldhanotiya** [comment]
Please change `name` to `item` into selected value arrow function something like this

> selectedValue={(index,item) => this._selectedValue(index, item)}

**Comment by nkbeldar** [comment]
ok Thanq u bro....
