### ISSUE TITLE
Fail when build for Ios

### ISSUE THREAD

**Issue by sewerrat** [vishaldhanotiya/react-native-modal-picker#12]
I got this error when building on Ios. Pls show me how to fix
`
No profile for team 'Q84UD28472' matching 'XXXWildCard' found: Xcode couldn't find any provisioning profiles matching 'Q84UD28472/XXXXWildCard'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the General tab of the target editor. (in target 'RNModalPicker')
`
Thanks!

**Comment by vishaldhanotiya** [comment]
If you need to run this project on device you need to IOS provisioning profile and certificates. You can generate certificate form Apple developer account/console or if you don't have apple developer account you can run this project on simulator.

**Comment by sewerrat** [comment]
Actually I already run build my project, and I include your picker into my new version. I build succeed on Android, but I got error with this version. The above error I think maybe I changed react-native version. 
But when I go back old version, I got this error 

> 'React/RCTBundleURLProvider.h' file not found

Do you have any ideas?
Thanks so much!

**Comment by sewerrat** [comment]
Hi! I found something when rerun pod install:  
```
[!] use_native_modules! skipped the react-native dependency 'rn-modal-picker'. No podspec file was found.
    - Check to see if there is an updated version that contains the necessary
    podspec file
    - Contact the library maintainers or send them a PR to add a podspec. The
    react-native-webview podspec is a good example of a package.json driven
    podspec. See
```   
I think it's reason why I got above errors. Can you check? Thanks so much!

**Comment by vishaldhanotiya** [comment]
Hello @sewerrat 
Please check latest version of this npm package, We have resolved this issue in this version
npm i rn-modal-picker@0.2.7
 
This issue generate because of react native support **Automatic linking** from 0.60.0, so we updated our npm package according to it.
