### ISSUE TITLE
Add Horizontal Line

### ISSUE THREAD

**Issue by edoofx** [vishaldhanotiya/react-native-modal-picker#14]
how to add horizontal line for each item ?

trying add underline text at this style :
```
  listTextViewStyle: {
    color: '#000',
    marginVertical: 15,
    flex: 0.9,
    marginLeft: 20,
    marginHorizontal: 10,
    textAlign: 'left',
},
```

but only underline at text, not item

**Comment by vishaldhanotiya** [comment]
Hii @edoofx,

We added `itemSeparatorStyle` props for a horizontal line between items

```
 itemSeparatorStyle:{
    height: 1,
    width: "90%",
    alignSelf: "center",
    backgroundColor: "#D3D3D3"
  }
```

Thank you for the report to feature
