### ISSUE TITLE
Search any character in the search like statement in SQL

### ISSUE THREAD

**Issue by keremburak** [vishaldhanotiya/react-native-modal-picker#16]
Hi vishaldhanotiya,

Thanks for this nice picker. I am a beginner about RN. 
I want to show all results when I enter any characters in the search bar. But, it deosnt show any result like. The results are shown only if I type all true word. 

I expect this search bar as 'LIKE' statement in SQL. 

How can I achieve this functionality?

Thanks in advance.

**Comment by vishaldhanotiya** [comment]
Hii @keremburak,
