### ISSUE TITLE
The Items in the Modal Picker are not showing 

### ISSUE THREAD

**Issue by ZaidQ797** [vishaldhanotiya/react-native-modal-picker#21]
Hello everyone,I'm using rn-picker-modal and I'm trying to render data from state,but data is rendering and showing shwoing on the modal.when I click somewhere in the modal the item is selected and displayed on the placeholder place.But items can't be show when modal open.
![Screenshot_1594982106](https://user-images.githubusercontent.com/53520463/87777738-76388100-c843-11ea-8ad5-676d764e2dea.png)
![Screenshot_1594982101](https://user-images.githubusercontent.com/53520463/87777745-789adb00-c843-11ea-941e-a72fec0d71dc.png)

**Comment by Homitag12** [comment]
Same issue

**Comment by TaylorDale** [comment]
Also having the same problem

**Comment by vishaldhanotiya** [comment]
FIxed issue in version 0.4.5.
Thanks
