### ISSUE TITLE
Undefined is not an object, evaluating 'data.filter'

### ISSUE THREAD

**Issue by hamza-fayyaz** [vishaldhanotiya/react-native-modal-picker#25]
Get an error while searching ("Undefined is not an object, evaluating 'data.filter' ")
<img width="306" alt="Screenshot 2020-09-13 at 3 00 50 PM" src="https://user-images.githubusercontent.com/63796859/93015313-efe5b480-f5d1-11ea-8e18-ffc78ebf711d.png">

**Comment by thorapps** [comment]
how did you solve it? I'm having same issue
