### ISSUE TITLE
xcode build fails

### ISSUE THREAD

**Issue by deflorilemarului** [vishaldhanotiya/react-native-modal-picker#3]
ios/build/Build/Intermediates.noindex/RNModalPicker.build/Debug-iphonesimulator/RNModalPicker.build/Script-00DD1BFF1BD5951E006B06BC.sh: line 3: ../node_modules/react-native/scripts/react-native-xcode.sh: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by vishaldhanotiya** [comment]
Hello, @deflorilemarului I have tested this library in IOs. it's working fine Please clear Xcode cache and retry it may solve your problem

**Comment by mtahir08** [comment]
I cleaned Xcode cache but still I see above issue. 
"react-native": "0.59.5",

**Comment by vishaldhanotiya** [comment]
Hello @mtahir08 and @deflorilemarului I think this issue generate because of react native version.
please check following answer 

https://github.com/facebook/react-native/issues/14935

https://github.com/getsentry/react-native-sentry/issues/141

**Comment by SnakeHead** [comment]
I have the same issue, fails to build. Using RN 0.57.8

**Comment by ririlya94** [comment]
same here.. it's not working for me.. for my case, whenever you install the rn-modal-picker and the app is existed in ios simulator, then this problem wont exist. It only happens whenever i have to reinstall the app (and the rn-modal-picker is already installed).. 1st and 2nd solution from @vishaldhanotiya didn't work for me.. The third one i'm still trying.. I'm using RN 0.54.1..

**Comment by winadiw** [comment]
same here, build issue.

**Comment by majidnasirinejad** [comment]
same problem here. not working on iOS

**Comment by alfathdirk** [comment]
try ```react-native unlink rn-modal-picker``` and re-run ```react-native run-android``` without remove the package..hope this help

**Comment by vishaldhanotiya** [comment]
Hello @All

**Comment by vishaldhanotiya** [comment]
Hello @ALL

Can you please check latest version of this npm package. we test this package with new and old both version it is working fine. if any one if any issue let me know i will try to coordinate with you 

> npm i rn-modal-picker@0.2.7

Happy coding...:)
