### ISSUE TITLE
How to change the default height of modal picker

### ISSUE THREAD

**Issue by harry021** [vishaldhanotiya/react-native-modal-picker#34]
For one or two items it shows a default height. And leave a blank space at the end. If we have more items in the flatlist it adjust its height according to them.

**Comment by harry021** [comment]
Can you add listDataContainerStyle as a prop. I need to modify this.

**Comment by papiahs** [comment]
Hello I've same problem, when the list has few items, it display small height, and cannot show all items
![imagen](https://user-images.githubusercontent.com/967703/120321024-33479680-c2b9-11eb-9aaa-8f865330ecd1.png)

**Comment by harry021** [comment]
> Hello I've same problem, when the list has few items, it display small height, and cannot show all items
> ![imagen](https://user-images.githubusercontent.com/967703/120321024-33479680-c2b9-11eb-9aaa-8f865330ecd1.png)

**Comment by harry021** [comment]
If author can add  listDataContainerStyle as a prop, than we can modify it. i guess it will solve our problem.

**Comment by papiahs** [comment]
As a workaround, change the style in index.js, flatListStyle. But it would be great if it is exposed. So I left it and when you rotate the phone it no longer fails. This happened to me on a moto Z3 play and a samsung S8 

  flatListStyle: {
    maxHeight: "85%",
    marginBottom:15
  }

**Comment by vishaldhanotiya** [comment]
#Fixed we removed minHeight style from list.
