### ISSUE TITLE
IOS can not open the suggestion if not clicked at the arrow.

### ISSUE THREAD

**Issue by Tuan0304** [vishaldhanotiya/react-native-modal-picker#39]
First of all, great work with the picker. cant complain. But i'm having an issue. My app run this picker on android work perfectly, but on IOS, i have to press at the arrow to open the modal. can anyone help me? really appreciate it.

**Comment by fclealobvia** [comment]
Same problem on IOS

**Comment by vishaldhanotiya** [comment]
FIxed issue in version 0.4.5.
Thanks
