### ISSUE TITLE
Sometimes the item list only shows 10 items!

### ISSUE THREAD

**Issue by oxustudio** [vishaldhanotiya/react-native-modal-picker#49]
**Describe the bug**
Sometimes the item list only shows 10 items!

**To Reproduce**
click on the picker, choose the item and repeat the operation several times!

**Screenshots**
![image](https://github.com/vishaldhanotiya/react-native-modal-picker/assets/91684260/aa0bbe36-3168-4c95-9010-2698d842116e)

!! to redisplay all items
then just enter a space in the search then delete the space so that the list returns in full

Thanks.

**Comment by vishaldhanotiya** [comment]
@oxustudio Thanks for reporting this issue. We are working on it.
