### ISSUE TITLE
Warning: Failed prop type: Invalid props.style key `outlineStyle` supplied to `TextInput

### ISSUE THREAD

**Issue by abdulah-js** [vishaldhanotiya/react-native-modal-picker#57]
**Describe the bug**
I am getting this warning in console because of wrong style of outlineStyle

**To Reproduce**
![Screenshot 2024-06-11 at 23 29 40](https://github.com/vishaldhanotiya/react-native-modal-picker/assets/172258935/d440105e-f364-46f0-9b36-6e995fb49390)

**Comment by abdulah-js** [comment]
@vishaldhanotiya We need to remove this style from here.
```
/rn-modal-picker/modalPicker/SearchBar.tsx Line 71
```

![Screenshot 2024-06-11 at 23 32 26](https://github.com/vishaldhanotiya/react-native-modal-picker/assets/172258935/496fec3a-513e-4168-81db-41a807451138)

**Comment by vishaldhanotiya** [comment]
@abdulah-js Thanks for reporting this issue. I will check and resolve ASAP.

**Comment by vishaldhanotiyadev** [comment]
@abdulah-js In the new version of npm warning issue is resolved v0.4.7

**Comment by vishaldhanotiya** [comment]
@abdulah-js In the new version of npm warning issue is resolved v0.4.7
