### ISSUE TITLE
Return Value for selected Data. e.g return the ID for the selected value.

### ISSUE THREAD

**Issue by alvinego** [vishaldhanotiya/react-native-modal-picker#62]
**When value is selected? attributes of the value should be returned in another property.
**Describe the solution you'd like**
onSelect should be possible to return the ID of item selected in the datasource

** I tried creating another function to return the ID by searching my data with selected value. But it's cumbersome and present a problem when we have two or more values with the same name.

**Additional context**

**Comment by vishaldhanotiya** [comment]
@alvinego The issue has been fixed in v0.4.9.

Now in the `onChange` you will get object For Example {id:1, name:India}

**Comment by alvinego** [comment]
Seen. Thanks Chief
