### ISSUE TITLE
Get the other properties of the selected item other than name.

### ISSUE THREAD

**Issue by bbeckk** [vishaldhanotiya/react-native-modal-picker#7]
How to get the selected id as well? Usually we have to show the name and pass the id to the server. Can we get the selected id or selected phoneCode as well just like selected name??

> dataSource: [
>         {
>           id: 1,
>           name: "Afghanistan",
>           phoneCode: "0",
>         },
>         {
>           id: 3,
>           name: "Bahrain",
>           phoneCode: "00",
>         },
>         {
>           id: 4,
>           name: "Canada",
>           phoneCode: "000",
>         }
>       ],

**Comment by vishaldhanotiya** [comment]
Hello @bbeckk ,

We modified npm package now we can access any key of json. Please check latest version of npm

``npm i rn-modal-picker@0.2.4``

**Comment by alvinego** [comment]
How to access this please?

**Comment by vishaldhanotiya** [comment]
> How to access this please?

Fixed this issue in V0.4.9
