### ISSUE TITLE
No podspec file was found

### ISSUE THREAD

**Issue by gabrielarantes** [vishaldhanotiya/react-native-modal-picker#8]
I had a problem when try run my app on ios simulator. It's showing the following error:

[!] use_native_modules! skipped the react-native dependency 'rn-modal-picker'. No podspec file was found.

RN - 0.61.1.

**Comment by Thilagavathi1** [comment]
@vishaldhanotiya Any updates on this issue. I too facing the same issue.

**Comment by sewerrat** [comment]
@vishaldhanotiya I faced same issue. Please help!

**Comment by vishaldhanotiya** [comment]
Hello @Thilagavathi1 
Please check latest version of this npm package, We have resolved this issue in this version
npm i rn-modal-picker@0.2.7

This issue generate because of react native support Automatic linking from 0.60.0, so we updated our npm package according to it.
